# shows issue in distributed last versions


## Usage

```bash
pip install -r requirements.txt
pytest --asyncio-mode=auto -xv
```

## History

- from 2023.4.0 issue running test_submit_future_with_resources_and_published_dataset
- from 2023.7.0 issue in running both tests


